#!/usr/bin/env bash

#clear
file="$1"
file_key="$2"

if test -s "$file"; then
  unset check_alg
  check_alg="$(avbtool info_image --image "$file" 2>/dev/null | awk '/^Algorithm:/ { print $2 }')"

  if test "$check_alg" != "NONE" -a ! -z "$check_alg"; then

    #f_name="$(echo "$file" | awk -F"." '{ print $1 }')"
    r="$(basename $file)"

    f_name=${r%.*}

    #offset_avb="$(printf "%d\n" "$(bin_utils foffset "$file" "41564230" -1)")"

    offset_avb="$(bin_utils foffset "$file" "41564230" -1 true)"

    if test ! -z "$offset_avb"; then

      size_magic="$(avbtool info_image --image "$file" | awk '/Header Block:/ { print $3 }')"

      size_ayten="$(avbtool info_image --image "$file" | awk '/Authentication Block:/ { print $3 }')"

      xxx="$(expr "$offset_avb" \+ 64)"

      offset_key="$(printf "%d\n" "0x""$(xxd -ps -s "$xxx" -l 8 "$file")")"

      xxx="$(expr "$offset_avb" \+ 72)"

      size_key="$(printf "%d\n" "0x""$(xxd -ps -s "$xxx" -l 8 "$file")")"

      size_new_key="$(stat -c %s "$file_key")"

      real_offset_key_dec="$(expr "$offset_avb" \+ "$size_magic" \+ "$size_ayten" \+ "$offset_key")"

      real_offset_key="$(printf "%x\n" "$real_offset_key_dec")"

      real_size_key="$(expr "$real_offset_key_dec" \+ "$size_key")"

      if test "$size_key" == "$size_new_key"; then

        sha11="$(avbtool info_image --image "$file" | awk '/^Public key \(sha1\):/ { print $4}')"

        bin_utils writekey "$file" "$real_offset_key" -f "$file_key" &>/dev/null

        if [ $(echo $?) -eq 0 ]; then
          check_new_alg="$(avbtool info_image --image "$file" 2>/dev/null | awk '/^Algorithm:/ { print $2 }')"

          sha12="$(avbtool info_image --image "$file" | awk '/^Public key \(sha1\):/ { print $4}')"

          if [ ! -z "$sha11" -a ! -z "$sha12" ]; then
            echo
            echo ".....Algorithm: $check_new_alg"
            echo ".....sha1 public key: $sha12"
            echo
          else
            echo ".....$error_change_key!"
            echo
          fi
        else
          echo ".....$error_change_key!"
          echo
        fi
      else
        echo
        echo ".....$error_key_sizes_do_not_match"
        echo
      fi
    else
      echo
      echo ".....$error_not_found offset AVB0"
      echo
    fi
  else
    echo
    echo ".....$f_i_l_e $nd/$file $not_signed!"
    echo
  fi
else
  echo
  echo ".....$no_file_to_process!"
  echo
fi
unset xxx
