#!/usr/bin/env bash

cd "$nb"

br_name=$(echo $file | sed 's!.*\/!!' | awk -F".new.dat.br" '{ print $1 }')

if test -s "$br_name".transfer.list; then
  echo
  echo ".....$converting "$br_name".new.dat.br..."
  $binary_dir/brotli -df "$br_name".new.dat.br -o "$br_name".new.dat 2>/dev/null

  if [ $(echo $?) -eq 0 ]; then
    echo
    echo ".....$converting "$br_name".new.dat..."
    echo
    python3 $local_dir/python/sdat2img.py "$br_name".transfer.list "$br_name".new.dat "$br_name".img
    if [ $(echo $?) -eq 0 ]; then
      echo
      echo ".....$deliting "$br_name".new.dat..."
      rm -f $PWD/"$br_name".new.dat
      file="$nb"/"$br_name".img
      nd="$nb"
      . $binary_dir/unpack_img
    else
      echo
      echo ".....$convert_error "$br_name".new.dat"
      echo
    fi
  else
    echo
    echo ".....$convert_error "$br_name".new.dat.br"
    echo
  fi
else
  echo
  echo ".....$file_not_found "$br_name".transfer.list."
fi
