#!/run/current-system/sw/bin/bash

hoho="/home/arsham/rosemary/UKL/UnpackerSystem"

# Directories to clean (Modify this list)
TARGET_DIRS=(
    "$hoho/system_ext_a/app"
    "$hoho/system_ext_a/priv-app"
    "$hoho/system_a/system/app"
    "$hoho/system_a/system/priv-app"
    "$hoho/system_a/system/system_ext/app"
    "$hoho/system_a/system/system_ext/priv-app"

    "$hoho/product_a/app"
    "$hoho/product_a/priv-app"
    "$hoho/product_a/data-app"
    "$hoho/product_a/pangu/system/app"
    "$hoho/product_a/pangu/system/priv-app"

    "$hoho/mi_ext_a/product/app"
    "$hoho/mi_ext_a/product/priv-app"
    "$hoho/mi_ext_a/product/data-app"
    "$hoho/mi_ext_a/system/app"
    "$hoho/mi_ext_a/system/priv-app"
    "$hoho/mi_ext_a/system/data-app"

    "$hoho/vendor_a/app"
    "$hoho/vendor_a/priv-app"
)

# Folders to remove
FOLDERS_TO_REMOVE=(
    # Android GO
    "Chrome"
    "com.google.mainline.go.telemetry"
    "DuoGo"
    "GoogleOne"
    "MiGalleryLockScreenGlobalGO"
    "AssistantGo"
    "GoogleDialerGo"
    "DuoGo"
    "MiPicks"
    "TraceurGo"
    "BugreportGo"
    "AnalyticsCoreGo"
    "GoogleSearchGo"
    "MessagesGo"
    "AutoTest"
    "GFTest"
    "MiBrowserLite"
    "GlobalCleanerGo"

    # A14 hos
    "MIUIVideo"
    "MIUIVipAccount"
    "ThirdAppAssistant"
    "MiRadio"
    "MIGalleryLockscreen-MIUI15"
    "MiBugReport"
    "LogManager"
    "MiuiContentCatcherMIUI15"
    "MIUITouchAssistant"
    "MIUIGuardProvider"
    "SystemHelper"
    "XMDualCameraCaliO16"
    "MIUIPersonalAssistantPhoneO16"
    "MiLauncherGlobal"
    "MIUICloudBackup"
    "MiGameCenterSDKService"

    # A13 HOS
    "MIRadioGlobal"
    "MiuiBiometric33148"
    "MiuiBugReportGlobal"
    "GoogleNews"
    "MiGalleryLockScreenGlobal"
    "Podcasts"
    "Turbo"
    "cit"
    "SettingsIntelligence"
    "PrivateComputeServices"
    "Longcheer_GFTest"
    "Longcheer_SensorTestTool"

    # Miui 14 CN
    "MIGalleryLockscreen-T"
    "BHPService"
    "MiuiBiometric33127"
    "mi_connect_service_t"
    "SimActivateService"
    "SogouInput"
    "MiGameService_MTK"
    "XiaoaiRecommendation"
    "OtaProvision"
    "com.iflytek.inputmethod.miui"
    "MIUIPersonalAssistant"
    "VoiceTrigger"
    "MIUIMirrorSmarthubNoneFeature"
    "CatcherPatch"
    "KSICibaEngine"
    "MiuiContentCatcher"
    "MIUINewHome_Removable"
    "MIUIgreenguard"
    "com.xiaomi.macro"
    
    # Miui 14 GL
    "HotwordEnrollmentOKGoogleCORTEXM4"
    "HotwordEnrollmentXGoogleCORTEXM4"
    "MIUIGlobalMinusScreen"
    "MiGalleryLockScreenGlobalT"
    "POCOCOMMUNITY_OVERSEA"
    "POCOSTORE_OVERSEA"



    "Traceur"
    "MIUIMiRcsGlobal"
    "SearchSelector"
    "AiCore_V"
    "VelvetCtS"
    "MIUIAICR"
#    "MIUIThemeManagerGlobal" # ******************
    "facebook-appmanager"
    "facebook-installer"
    "facebook-services"
    "MiuiDaemon"
    "MDMConfig"
    "MDMLSamples"
    "MDMLSample"
    "MipayService"
    "talkback"
    "mi_connect_service"
    "SoterService"
    "PaymentService"
    "MSA"
    "MIUISuperMarket"
    "MIUICloudService"
    "MIUIMiCloudSync"
    "MIUIAiasstService"
    "MIUIAccessibility"
    "MINextpay"
    "IFAAService"
    "HybridPlatform"
    "GoogleLocationHistory"
    "CarWith"
    "AnalyticsCore"
    "AiasstVision"
    "AiAsstVision"
    "MIUIReporter"
    "Updater"
    "XiaomiRecommendation"
    "XiaomiSimActivateService"
    "VoiceAssistAndroidT"
    "SogouIME"
    "MiBugReportOS2"
    "UPTsmService"
    "Chrome64"
    "com.google.mainline.adservices"
    "com.google.mainline.telemetry"
    "CatchLog"
    "com.xiaomi.ugd"
    "Drive"
    "Gmail2"
    "Biometric"
    "MiuiBiometric"
    "GoogleLocationHistory"
    "Maps"
    "Meet"
    "MiBugReportOS2Global"
    "mi_connect_service"
    "MiTrustService"
    "MiuiCit"
    "MIUICloudServiceGlobal"
    "MIUIGuardProviderGlobal"
    "MIUIHealthGlobal"
    "MIUIMiCloudSync"
    "MIUISystemAppUpdater"
    "MIUITouchAssistantGlobal"
    "MSA-Global"
    "Photos"
    "PlayAutoInstallStubApp"
    "SimActivateServiceGlobal"
    "SpeechServicesByGoogle"
    "SwitchAccess"
    "talkback"
    "Updater"
    "Videos"
    "YTMusic"
    "YouTube"
    "MiGameSDKService"
    "MIUIYellowPage"
    "MIUIQuickSearchBox"
    "MIUIPersonalAssistantPhoneOS2NoBeta"
    "MIUIBrowser"
    "AndroidAutoStub"
    "Backup"
    "DeviceIntegrationService"
    "DownloadProviderUi"
    "FamilyLinkParentalControls"
    "GoogleRestore"
    "HotwordEnrollmentOKGoogleRISCV"
    "HotwordEnrollmentXGoogleRISCV"
    "LinkToWindows"
    "MIServiceGlobal"
    "MIUIAccessibility"
    "MIUICleanMasterGlobal-cleaner"
    "MIUICloudBackupGlobal"
    "MIUIMusicGlobal"
    "MIUIVideoPlayer"
    "PersonalSafety"
    "Wellbeing"
    "Velvet"
    "wps-lite"
    "iFlytekIME"
    "SmartHome"
    "OS2VipAccount"
    "MiShop"
    "MIpay"
    "MIUIYoupin"
    "MIUIXiaoAiSpeechEngine"
    "MIUIVirtualSim"
    "MIUIMusicT"
    "MIUIMiDrive"
    "MIUIHuanji"
    "MIUIGameCenter"
    "MIUIEmail"
    "MIUIDuokanReader"
    "MIUICleanMaster"
    "Health"
    "BaiduIME"
    "DownloadProviderUI"
    "MIService"
    "MiGalleryLockScreenGlobalOs020"
    "MIUINotes"
    "MiuiScanner"
    "IFAAService"
    "CalendarGoogle"
    "GameCenterGlobal"
    "GoogleContacts"
    "GoogleOne_arm64"
    "MIUIMiPicks"
    "PaymentService_Global"
    "SoterService"
    "GlobalWPSLITE"
    "GoogleNews_xxhdpi"
    "MICOMMUNITY_OVERSEA"
    "MIDrop"
    "MISTORE_OVERSEA"
    "MIUIHuanjiGlobal"
    "SmartHome"
    "GoogleAssistant"
    "AppBox"
    "GoogleDialer_arm64"
    "AppCenter"
    "HealthConnectStub"
    "AppCloud"
    "Messages_arm64_xxhdpi"
    "bygIgnite"
    "MIBrowserGlobal_builtin_before_2021"
    "com.altice.android.myapps"
    "com.dti.telefonica"
    "MIUIEsimLPA"
    "com.sfr.android.sfrjeux"
    "MIUIGlobalMinusScreenWidget"
    "MIUIYellowPageGlobal"
    "CotaService"
    "OrangeManualSelector"
    "CrossDeviceServices"
    "AppEnabler"
    "AppSelector"
)

# Iterate over each target directory
for TARGET_DIR in "${TARGET_DIRS[@]}"; do
    if [[ -d "$TARGET_DIR" ]]; then
        for folder in "${FOLDERS_TO_REMOVE[@]}"; do
            FULL_PATH="$TARGET_DIR/$folder"
            if [[ -d "$FULL_PATH" ]]; then
                echo "🗑️  Removing: $FULL_PATH"
                rm -rf "$FULL_PATH"
            fi
        done
    fi
done

echo "🎉 Cleanup complete!"